// Generated by CoffeeScript 1.4.0
var AccountsPayments, CancelSubscription, EatLater, EatNow, EatNowRestaurant, FullMenuRestaurant, Home, LunchDate, ManageSubscriptions, RestaurantSubscriptionActive, Subscribe, Today, Tomorrow, app;

app = angular.module("app", []);

Kinvey.init({
  appKey: "kid_PVFkQeQG5M",
  appSecret: "7344648832814206b968007528346f52"
});

Home = function($scope) {
  $scope.firstName = "";
  $scope.lastName = "";
  return $scope.saveSettings = function() {
    var user;
    user = Kinvey.getCurrentUser();
    user.set("first_name", $scope.firstName);
    user.set("last_name", $scope.lastName);
    return user.save();
  };
};

EatNow = function($scope, $rootScope, $http, $timeout) {
  $scope.showMap = false;
  $scope.search = "";
  $scope.favorites = [
    {
      name: "Boloco",
      address: "Mass Ave",
      discount: "10",
      id: "xxxx"
    }, {
      name: "Boloco",
      address: "Mass Ave",
      discount: "10",
      id: "xxxx"
    }
  ];
  $scope.nearbys = [
    {
      name: "Boloco",
      address: "Mass Ave",
      discount: "10",
      id: "xxxx"
    }
  ];
  $scope.furthers = [
    {
      name: "Boloco",
      address: "Mass Ave",
      discount: "10",
      id: "xxxx"
    }
  ];
  $scope.location = [52.2100, 0.1300];
  $scope.select = function(id) {
    console.log("select", arguments);
    $rootScope.$emit("changeEatNowRestaurant", id);
    return $.mobile.changePage("#pageEatNowRestaurant");
  };
  $scope.doSearch = function() {
    var req, url, user;
    user = Kinvey.getCurrentUser();
    url = "/favorites?id=" + user.get("_id");
    req = $http.get(url);
    req.success(function(data, status, headers, config) {
      return $scope.favorites = data.favorites;
    });
    req.error(function(data, status, headers, config) {});
    url = "/nearbys?q=" + $scope.search + "&loc=" + $scope.location + "&within=" + 1600;
    req = $http.get(url);
    req.success(function(data, status, headers, config) {
      return $scope.nearbys = data.nearbys;
    });
    req.error(function(data, status, headers, config) {});
    url = "/furthers?q=" + $scope.search + "&loc=" + $scope.location;
    req = $http.get(url);
    req.success(function(data, status, headers, config) {
      return $scope.furthers = data.furthers;
    });
    return req.error(function(data, status, headers, config) {});
  };
  return $scope.tap = function(map) {
    var x;
    $scope.showMap = map;
    return $timeout(x = function() {
      console.log($scope.showMap);
      return $timeout(x, 1000);
    }, 1000);
  };
};

EatLater = function($scope) {};

Today = function($scope) {};

Tomorrow = function($scope) {};

Subscribe = function($scope) {};

LunchDate = function($scope) {};

ManageSubscriptions = function($scope) {};

AccountsPayments = function($scope) {};

EatNowRestaurant = function($scope, $rootScope, $timeout) {
  var countDown, startCountDown, started, stopCountDown;
  $scope.name = "Boloco";
  $scope.quantitySelected = "1";
  $scope.timeLeft = 100;
  $scope.itemSelected = "Beef Taco";
  $scope.favorites = ["Beef Taco", "Chicken Burrito", "Rice & Bean Plate", "Steak Burrito"];
  $scope.discount = 10;
  started = false;
  startCountDown = function() {
    if (started) {
      return;
    }
    started = true;
    return countDown();
  };
  stopCountDown = function() {
    started = false;
    return countDown();
  };
  countDown = function() {
    var x;
    return $timeout(x = function() {
      $scope.timeLeft--;
      if (started) {
        return $timeout(x, 1000);
      }
    }, 1000);
  };
  $rootScope.$on("changeEatNowRestaurant", function(e, id) {
    return startCountDown();
  });
  return $scope.twoDigits = function(number) {
    return ("0" + (parseInt(number))).slice(-2);
  };
};

RestaurantSubscriptionActive = function($scope) {};

CancelSubscription = function($scope) {};

FullMenuRestaurant = function($scope) {
  var calculateTotal;
  $scope.selectedQuantity = "1";
  $scope.menus = [
    {
      name: "Bangkok Thai Burrito",
      price: 5.99
    }, {
      name: "Buffalo Burrito",
      price: 5.99
    }, {
      name: "Chips & Guacamole",
      price: 2.69
    }
  ];
  $scope.selectedMenu = $scope.menus[0];
  $scope.name = "Boloco";
  $scope.carts = [
    {
      name: "Buffalo Burrito",
      quantity: 1,
      price: 5.99
    }, {
      name: "Chips & Guacamole",
      quantity: 1,
      price: 2.69
    }
  ];
  $scope.total = 7.68;
  calculateTotal = function() {
    return $scope.total = $scope.carts.reduce(function(itema, itemb) {
      return {
        price: itema.price + itemb.price
      };
    }).price;
  };
  calculateTotal();
  $scope.addToCart = function() {
    $scope.carts.push({
      name: $scope.selectedMenu.name,
      price: $scope.selectedMenu.price,
      quantity: $scope.selectedQuantity
    });
    return calculateTotal();
  };
  $scope.oneClick = function() {};
  return $scope.checkOut = function() {};
};
