// Generated by CoffeeScript 1.4.0
var AccountPayment, EatLater, EatNow, EatNowBoloco, EatNowMap, GraphCtrl, Home, LunchDate, ManageSubscriptions, Subscribe, Today, Tomorrow, app;

app = angular.module("app", []);

Home = function($scope) {};

EatNow = function($scope) {};

EatLater = function($scope) {};

EatNowMap = function($scope) {};

Today = function($scope) {};

Tomorrow = function($scope) {};

Subscribe = function($scope) {};

LunchDate = function($scope) {};

ManageSubscriptions = function($scope) {};

AccountPayment = function($scope) {};

EatNowBoloco = function($scope) {};

GraphCtrl = function($scope) {};

$(function() {
  var data, plot;
  console.log("done");
  data = [
    {
      label: "Discounts",
      data: [[1, 1], [5, 5], [10, 10]]
    }
  ];
  plot = $.plot($("#placeholder"), data, {
    series: {
      bars: {
        horizontal: true,
        show: true
      }
    },
    grid: {
      show: true,
      clickable: true
    }
  });
  return $("#placeholder").bind("plotclick", function(event, pos, item) {
    if (item) {
      $("#clickdata").text("You clicked point " + item.dataIndex + " in " + item.series.label + ".");
      return plot.highlight(item.series, item.datapoint);
    }
  });
});

$(function() {
  var css_id, data, options;
  css_id = "#placeholder";
  data = [
    {
      label: "foo",
      data: [[1, 300], [2, 300], [3, 300], [4, 300], [5, 300]]
    }, {
      label: "bar",
      data: [[1, 800], [2, 600], [3, 400], [4, 200], [5, 0]]
    }, {
      label: "baz",
      data: [[1, 100], [2, 200], [3, 300], [4, 400], [5, 500]]
    }
  ];
  options = {
    series: {
      stack: 0,
      lines: {
        show: false,
        steps: false
      },
      bars: {
        show: true,
        barWidth: 0.9,
        align: "center"
      }
    },
    xaxis: {
      ticks: [[1, "One"], [2, "Two"], [3, "Three"], [4, "Four"], [5, "Five"]]
    }
  };
  $(css_id).bind("plotclick", function(event, pos, item) {
    return console.log(arguments);
  });
  return $.plot($(css_id), data, options);
});
